### ISSUE TITLE
Example data loader format

### ISSUE THREAD

**Issue by IgorVG** [MIC-DKFZ/RegRCNN#3]
To train it on RGB images I created a custom dataloader thought it seems not to be possible to use 3 input channels in parallel. Slight modifications of dataloader and config files created some errors showing deeper dependencies on having single input channel.
Is there any regular way for RGB if I missed something ?

**Comment by Gregor1337** [comment]
Hi Igor,
if you start-off your own dataset with the included toy dataset configs and dataloader as a blueprint, you should be able to include multiple channels in your data.
E.g., in configs 
        self.channels = [0,1,2]
        self.n_channels = len(self.channels)
would be an option to include the first three channels of your data.

Otherwise, please supply your configs and dataloader so I can take a look.
Best,
Greg

**Comment by Gregor1337** [comment]
I'm closing this due to no new developments.
